name: Check Linux Support

run-name: Checking Linux support for ${{ github.actor}}

on: [push]


jobs:
  check-c-compile:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: leafo/gh-actions-lua@v9
        with:
          LuaVersion: "5.2.4"

      - run: echo -e "#include <stdio.h>\n#include <include.h>\nint main(){\nfprintf(stdout, \"%d\", GetTime());\nreturn 0;\n}" >> main.c
      - run: mkdir include && mkdir lib
      - run: echo -e "extern int GetTime();" >> include/include.h && echo -e "#include <math.h>\nint GetTime(){\nreturn sqrt(4);\n}" >> lib/test.c
      - run: ./install.sh DEBUG
      - run: lua lmake --build-dir . --lib-dirs lib/ --include-dirs include/ --flags -O2 -lm -o --librarys m --includes stdio math include --language c --compiler gcc --files main.c lib/test.c --name test --build-objects

  check-c-library-compile:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: leafo/gh-actions-lua@v9
        with:
          LuaVersion: "5.2.4"

      - run: echo -e "int GetTime(){return 5;}" >> main.c
      - run: ./install.sh DEBUG
      - run: lua lmake --build-dir . --language c --compiler gcc --flags -O2 -fPIC -c --files main.c --build-objects --c-shared
